// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSasfJdTr6350cdjrmVnDF4Xmi4nry5dM',
    appId: '1:373545210888:web:d7dbff3583f4ad21e12dbd',
    messagingSenderId: '373545210888',
    projectId: 'prof-34ef2',
    authDomain: 'prof-34ef2.firebaseapp.com',
    storageBucket: 'prof-34ef2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnoew4fugrGBiFlvVcOuPQPXk3Vs9mH7c',
    appId: '1:373545210888:android:b710946759ea872de12dbd',
    messagingSenderId: '373545210888',
    projectId: 'prof-34ef2',
    storageBucket: 'prof-34ef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6NaqQMHySiZJexi9mjjhiWfEeHDcG8No',
    appId: '1:373545210888:ios:3eb91f17d67b2262e12dbd',
    messagingSenderId: '373545210888',
    projectId: 'prof-34ef2',
    storageBucket: 'prof-34ef2.appspot.com',
    iosClientId: '373545210888-ai6n7m19rcl2cvjsao3sbbk3pddj88b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.profilepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6NaqQMHySiZJexi9mjjhiWfEeHDcG8No',
    appId: '1:373545210888:ios:3eb91f17d67b2262e12dbd',
    messagingSenderId: '373545210888',
    projectId: 'prof-34ef2',
    storageBucket: 'prof-34ef2.appspot.com',
    iosClientId: '373545210888-ai6n7m19rcl2cvjsao3sbbk3pddj88b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.profilepage',
  );
}
